# platform_windows.cmake
# Windows-specific build configuration: Windows App SDK paths, C++/WinRT flags,
# and linker inputs. Included by frontend/windows/CMakeLists.txt.
#
# Prerequisites (run once in frontend/windows/):
#   winget install Microsoft.winappcli
#   cd frontend/windows && winapp init . --use-defaults --setup-sdks stable
# After cloning:
#   cd frontend/windows && winapp restore

# ---------------------------------------------------------------------------
# Architecture selection
# ---------------------------------------------------------------------------
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(EWCALC_WIN_ARCH "x64")
else()
    set(EWCALC_WIN_ARCH "arm64")
    message(WARNING "platform_windows: arm64 build is untested")
endif()

# ---------------------------------------------------------------------------
# Windows App SDK paths (relative to frontend/windows/)
# .winapp/ is generated by winapp init/restore and gitignored.
# ---------------------------------------------------------------------------
# CMAKE_CURRENT_SOURCE_DIR here is the directory of the including CMakeLists.txt
# (i.e. frontend/windows/), so .winapp is a direct child.
set(EWCALC_WINAPP_DIR "${CMAKE_CURRENT_SOURCE_DIR}/.winapp")
set(EWCALC_WINAPP_INCLUDE "${EWCALC_WINAPP_DIR}/include")
set(EWCALC_WINAPP_LIB_DIR "${EWCALC_WINAPP_DIR}/lib/${EWCALC_WIN_ARCH}")

# Windows SDK lib path (installed with VS Build Tools / VS IDE)
cmake_path(SET EWCALC_WINSDK_LIB_DIR
    "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.26100.0/um/${EWCALC_WIN_ARCH}")

# ---------------------------------------------------------------------------
# Helper: apply Windows App SDK settings to a target
#
# Usage: ewcalc_configure_winui3_target(<target>)
# ---------------------------------------------------------------------------
function(ewcalc_configure_winui3_target TARGET)
    target_include_directories(${TARGET} PRIVATE "${EWCALC_WINAPP_INCLUDE}")

    # C++/WinRT requires these MSVC flags:
    #   /await:strict  — standard-compliant coroutines (C++20 co_await)
    #   /Zc:__cplusplus — report correct __cplusplus value (C++/WinRT checks it)
    #   /utf-8         — source and execution charset UTF-8
    target_compile_options(${TARGET} PRIVATE
        /await:strict
        /Zc:__cplusplus
        /utf-8
        /W4
        /permissive-
    )

    target_compile_definitions(${TARGET} PRIVATE
        NOMINMAX
        WIN32_LEAN_AND_MEAN
        WINRT_LEAN_AND_MEAN
        UNICODE
        _UNICODE
    )

    target_link_libraries(${TARGET} PRIVATE
        # Windows App SDK runtime bootstrap (for unpackaged / development use)
        "${EWCALC_WINAPP_LIB_DIR}/Microsoft.WindowsAppRuntime.Bootstrap.lib"
        "${EWCALC_WINAPP_LIB_DIR}/Microsoft.WindowsAppRuntime.lib"
        "${EWCALC_WINAPP_LIB_DIR}/Microsoft.UI.Dispatching.lib"
        "${EWCALC_WINAPP_LIB_DIR}/cppwinrt_fast_forwarder.lib"
        # Windows SDK umbrella libs (found via VS default search paths)
        WindowsApp.lib
        OneCoreUap.lib
    )
endfunction()
